# -*- coding: utf-8 -*-
"""chapter_5_pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aVHs8a_BdE5GISdauqkENhgauZ7A3qrg
"""

import pandas as pd
df = pd.DataFrame({
    "sale":[3,2,3,9,10,6],
    "signup":[5,5,6,12,14,13],
    "visits":[20,42,28,62,81,50],
},index = pd.date_range(start = "2003/06/08", end ="2022/06/08",periods = 6))

ax = df.plot.area()
ax

import pandas as pd
# df = pd.DataFrame({
#     "lab":["A","B",'C'],
#     "val":[10,30,20],
# })
# ax = df.plot.bar(x="lab" , y = "val",rot =259)

speed = [0.1, 17.5,40,48,52,69]
lifespan = [2.8, 70, 1.5,25,12,28]
index = ["snail","pig","elephant","rabbit","giffage","caro"]
df = pd.DataFrame({"speed":speed, "lifespan":lifespan},index = index)
ax = df.plot.bar(rot = 360,stacked = True,color = {'speed':"red","lifespan":"gray"})
print("----------")
ax = df.plot.bar(rot = 0,stacked = False)
print("--------")
axes = df.plot.bar(subplots = True)

import pandas as pd
import numpy as np 
df = pd.DataFrame(np.random.randn(4,3),
                  columns = ["Col1", "Col2","Col3"])
box_plot = df.boxplot(grid = False)
df['X'] = pd.Series(["A","A","B","B"])
df['Y'] = pd.Series(["A","B","A","B"])
box_plot = df.boxplot(column =["Col1", "Col2","Col3"],by =["X","Y"])

import pandas as pd
import numpy as np 
df = pd.DataFrame({
    "mass":[0.33,4.87,5.70],
    "radius":[2439,6051,6378],
},index = ["Mercuty", "Venus",'Earth'])
plot = df.plot.pie ( y = "mass",figsize = (5,5))
plot = df.plot.pie ( y = "radius",figsize = (11,5))